version: '3'


networks:
  pg-dev:
    external: true 
  redis:
    external: true
  traefik:
    external: true
      

services:
  comms: 
    hostname: comms 
    image: comms:latest
    restart: unless-stopped
    networks:
      - pg-dev
      - redis
      - traefik
    env_file: ./apps/comms/.env
    ports:
      - 54000:4000
    labels:
      - traefik.enable=true
      - traefik.http.routers.comms-api.rule=Host(`api.comms.p.kariukigeorge.me`)
      - traefik.http.routers.comms-api.tls=true
      - traefik.http.routers.comms-api.tls.certresolver=lets-encrypt
      - traefik.port=54000
  comms-web: 
    hostname: comms-web
    image: comms-web:latest
    restart: unless-stopped
    networks:
      - traefik
    env_file: ./apps/comms-web/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.comms.rule=Host(`comms.p.kariukigeorge.me`)
      - traefik.http.routers.comms.tls=true
      - traefik.http.routers.comms.tls.certresolver=lets-encrypt
      - traefik.port=55300
    ports:
      - 55300:3000
  comms-test: 
      hostname: comms-test
      image: comms-test:latest
      restart: unless-stopped
      networks:
        - traefik
      env_file: ./apps/comms-test/.env
      labels:
        - traefik.enable=true
        - traefik.http.routers.comms-test.rule=Host(`comms-test.p.kariukigeorge.me`)
        - traefik.http.routers.comms-test.tls=true
        - traefik.http.routers.comms-test.tls.certresolver=lets-encrypt
        - traefik.port=53000
      ports:
        - 53000:3000
    
    
    
        
    
